version: 2

jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha
        environment:
          TERM: dumb
          ANDROID_SDK_VERSION: 27
          ANDROID_BUILD_TOOLS_VERSION: 27.0.3
          JAVA_OPTS: -Xmx1536m
          GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx1536m -XX:+HeapDumpOnOutOfMemoryError"'

    working_directory: ~/EstudoWorkManager
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
      - run: gradle test
